'set line 1 1 1'
'draw shp ../../CONTORNOS/SHAPES/BRASIL.shp '
'set line 15 1 1'
'draw shp ../../CONTORNOS/SHAPES/contorno_Grande.shp '
'draw shp ../../CONTORNOS/SHAPES/contorno_iguacu.shp '
'draw shp ../../CONTORNOS/SHAPES/contorno_parana.shp '
'draw shp ../../CONTORNOS/SHAPES/contorno_paranaiba.shp '
'draw shp ../../CONTORNOS/SHAPES/contorno_paranapanema.shp '
'draw shp ../../CONTORNOS/SHAPES/contorno_sfrancisco.shp '
'draw shp ../../CONTORNOS/SHAPES/contorno_tiete.shp '
'draw shp ../../CONTORNOS/SHAPES/contorno_tocantins.shp '
'draw shp ../../CONTORNOS/SHAPES/contorno_uruguai.shp '
'draw shp ../../CONTORNOS/SHAPES/Jacui.shp'
'draw shp ../../CONTORNOS/SHAPES/itaipu.shp'

